### ISSUE TITLE
login email after installation is set to "Admnistrator"

### ISSUE THREAD

**Issue by beda42** [palcilibraries/CC-Plus#3]
I followed the installation documentation for CC-Plus and came up with a system I could not log into. After some debugging, I found that the email address I provided in the last installation step was not used for the administrator user, but instead the value of email in the database is set to "Administrator". Logging in with this value as email was successful.

**Comment by lsr2912** [comment]
This is intentional and by-design, but may need to be documented better. The email address requested during setup is attached to the consortium records, and is not (yet) used for anything. It's there for future use in sending alerts/updates/notices, etc.
