### ISSUE TITLE
From Usersnap - Password trouble

### ISSUE THREAD

**Issue by guegueng** [palcilibraries/CC-Plus#5]
**Sender**: shaddad@carroll.edu
**Comment**: My login information is not working right now - I can't tell if this is because I forgot my password or there is an issue with the site.  I think a forgot password link would be helpful either way though.
[Open #59 in Usersnap Dashboard](https://usersnap.com/a/#/your-team-58oj/p/cc-plus-8027182e/59)

<a href='https://usersnappublic.s3.amazonaws.com/2021-04-21/19-02/970a60ff-5880-49be-9047-8e6f4932be07.png'>![From Usersnap - Password trouble](https://usersnappublic.s3.amazonaws.com/2021-04-21/19-02/5d325b3e-f331-4866-9988-79dcc6bd3add.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2021-04-21/19-02/970a60ff-5880-49be-9047-8e6f4932be07.png'>Download original image</a>

**Browser**: Chrome 89 (Windows 10)
**Referer**: [http://192.129.227.34/login](http://192.129.227.34/login)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 937

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by lsr2912** [comment]
Login and password-recovery loop added with commit [9f85d8f](https://github.com/palcilibraries/CC-Plus/commit/9f85d8f75319ee56b91972f62399c6a7ced2f522) on 5/25/21. Requires .env configuration settings for outbound SMTP.
